#!/usr/bin/env bash
# Wrap the artifact-shaped fragment into a standalone page for GitHub Pages.
#
# pocket-critter.html is the source of truth and is deliberately headless:
# a published Claude artifact supplies its own <!doctype>/<head>/<body>, so
# the file must not carry them. Self-hosting is the opposite — it needs a
# real <head> for the og: tags to unfurl and for GoatCounter to load.
#
# Everything host-specific lives here, in one place:
#   - og:/twitter: tags        (inert in an artifact, real on Pages)
#   - GoatCounter count.js     (blocked by the artifact CSP, real on Pages)
#   - the small reset the artifact platform injects for us
#
# Usage: ./build.sh   ->   writes index.html
set -euo pipefail
cd "$(dirname "$0")"

SRC="pocket-critter.html"
OUT="index.html"
SITE="https://pratikpoddar.github.io/pocket-critter"

[ -f "$SRC" ] || { echo "missing $SRC" >&2; exit 1; }

{
cat <<HEAD
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>Pocket Critter</title>
<meta name="description" content="Adopt an original virtual pet. Feed it, play with it, send it to work. It never dies.">

<meta property="og:site_name" content="Pocket Critter">
<meta property="og:title" content="Pocket Critter — adopt a critter that never dies">
<meta property="og:description" content="Feed it, play with it, send it to work at the Soup Quality Testing department. A 30-second morning check-in for grown-up 90s kids.">
<meta property="og:type" content="website">
<meta property="og:url" content="$SITE/">
<meta property="og:image" content="$SITE/og-card.png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="A Lampmoth in its room, with hunger, happiness and energy meters.">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="Pocket Critter — adopt a critter that never dies">
<meta name="twitter:description" content="Feed it, play with it, send it to work. A 30-second morning check-in for grown-up 90s kids.">
<meta name="twitter:image" content="$SITE/og-card.png">

<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3Ctext y='.9em' font-size='90'%3E%F0%9F%90%BE%3C/text%3E%3C/svg%3E">

<!-- no_onload: the ?pet=xxxxxxxx deep link would otherwise register one
     distinct path per pet visited. The app counts its own routes. -->
<script>window.goatcounter = {no_onload:true};</script>
<script id="gcjs" data-goatcounter="https://pratikpoddar.goatcounter.com/count"
        async src="https://gc.zgo.at/count.js"></script>

<style>:root{color-scheme:light}body{margin:0}img{max-width:100%}[hidden]{display:none!important}</style>
</head>
<body>
<!-- GENERATED by build.sh from $SRC — edit that file, not this one. -->
HEAD

# the fragment carries its own <title> for the artifact gallery; the <head>
# above already set one, so drop it here rather than emit two.
grep -v '^<title>Pocket Critter</title>$' "$SRC"

cat <<'FOOT'
</body>
</html>
FOOT
} > "$OUT"

printf 'wrote %s (%s bytes)\n' "$OUT" "$(wc -c < "$OUT" | tr -d ' ')"
